### ISSUE TITLE
Error sh: Rscript: command not found

### ISSUE THREAD

**Issue by OwenHoare1989** [bvaldebenitom/SoloTE#59]
Dear @bvaldebenitom  

First of all thank you very much for developing this very useful pipeline. I am trying to run it on the output of the Cellranger pipeline using the bam file. In the first instance I am using this on the tansposable element TE.bed file which you included some script to make. However, I have the below error. But maybe I am wrong but I think this is coming from the following `"sh: Rscript: command not found"`

Is this becuase R needs to be installed to run the pipeline. The only way I was able to get the pipeline to run was to download the source code file and manually install the dependencies as mentioned in the tutorial. Could I confirm that the SoloTE outputs are being converted by Rscript into a matrix and that installing R in the same directory as the source code (uncompressed folder) should resolve this issue or is the error caused by something else.

Also, will this pipeline handle a custome made bed file with genes and all TEs not just at the family level but all TE fragments on all chromosomes amounting to millions of TEs ??

Thanks for any help you can provide. If something is not clear please feel free to ask.

```
samtools index Prefix_nogenes_overlappingtes.bam
bedtools bamtobed -i Prefix_nogenes_overlappingtes.bam -split > Prefix_nogenes_overlappingtes.bed
bedtools intersect -a /data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/SoloTE-1.09/hg38_rmsk.bed -b Prefix_nogenes_overlappingtes.bed -u > Prefix_selectedtes.bed
python /data/kdi_prod/.kdi/project_workspace_0/1092/acl/44.00/scRNA_seq_TE_Analysis/SoloTE-1.09/annotateBAM.py Prefix_nogenes_overlappingtes.bam Prefix_selectedtes.bed temp_annotated_te.bam 1



samtools sort -@ 4 -O BAM -o Prefix_teannotated.bam temp_annotated_te.bam
[bam_sort_core] merging from 13 files and 4 in-memory blocks...
samtools merge --threads 4 -o - /data/kdi_prod/.kdi/project_workspace_0/1092/acl/44.00/scRNA_seq_TE_Analysis/output_TEs/NIP_UGS_678_non_T_cells/outs/possorted_genome_bam.bam Prefix_teannotated.bam|samtools view -@ 4 -O BAM -o Prefix_final.bam -e 'exists([CB]) && exists([UB]) && exists([GN]) && [CB]!="-" && [UB]!="-" && [GN]!="-"' --keep-tag GN,CB,UB
samtools index Prefix_final.bam
Counts for chromosome chr1 are being generated in process: 32019
Counts for chromosome chr2 are being generated in process: 32020
Counts for chromosome chr3 are being generated in process: 32021
Counts for chromosome chr4 are being generated in process: 32022
Counts for chromosome chr5 are being generated in process: 32022
Counts for chromosome chr6 are being generated in process: 32021
Counts for chromosome chr7 are being generated in process: 32020
Counts for chromosome chr8 are being generated in process: 32022
Counts for chromosome chr9 are being generated in process: 32019
Counts for chromosome chr10 are being generated in process: 32021
Counts for chromosome chr11 are being generated in process: 32020
Counts for chromosome chr12 are being generated in process: 32022
Counts for chromosome chr13 are being generated in process: 32019
Counts for chromosome chr14 are being generated in process: 32021
Counts for chromosome chr15 are being generated in process: 32019
Counts for chromosome chr16 are being generated in process: 32022
Counts for chromosome chr17 are being generated in process: 32019
Counts for chromosome chr18 are being generated in process: 32021
Counts for chromosome chr19 are being generated in process: 32021
Counts for chromosome chr20 are being generated in process: 32020
Counts for chromosome chr21 are being generated in process: 32022
Counts for chromosome chr22 are being generated in process: 32020
Counts for chromosome chrM are being generated in process: 32022
Counts for chromosome chrX are being generated in process: 32019
Counts for chromosome chrY are being generated in process: 32020
Creating final results directory
/data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/output_TEs/NIP_UGS_678_tumor_cells/outs/Output_SoloTE/Prefix_SoloTE_output was created
Rscript /data/kdi_prod/.kdi/project_workspace_0/1092/acl/44.00/scRNA_seq_TE_Analysis/SoloTE-1.09/generate_mtx.R Prefix_legacytes.txt Prefix_legacytes_MATRIX
sh: Rscript: command not found
Traceback (most recent call last):
  File "/data/kdi_prod/.kdi/project_workspace_0/1092/acl/44.00/scRNA_seq_TE_Analysis/SoloTE-1.09/SoloTE_pipeline.py", line 272, in <module>
    os.rename(mtx_outname,finaldir+"/"+mtx_outname)
FileNotFoundError: [Errno 2] No such file or directory: 'Prefix_legacytes_MATRIX' -> '/data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/output_TEs/NIP_UGS_678_tumor_cells/outs/Output_SoloTE/Prefix_SoloTE_output/Prefix_legacytes_MATRIX'
sis/CondaEnvscRNA_seq) -bash-4.2$ /Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analys
sis/CondaEnvscRNA_seq) -bash-4.2$ /Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analys
sis/CondaEnvscRNA_seq) -bash-4.2$ /Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analys
sis/CondaEnvscRNA_seq) -bash-4.2$ /Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analys
sis/CondaEnvscRNA_seq) -bash-4.2$ /Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analys
sis/CondaEnvscRNA_seq) -bash-4.2$ /Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analys
sis/CondaEnvscRNA_seq) -bash-4.2$ /Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analys

```

**Comment by bvaldebenitom** [comment]
Hi @OwenHoare1989 ,

yes, you will need R in your PATH variable. You can download it from source code and then add it to your PATH, and should solve the issue.

Do you use conda environments? That would make this process a bit faster.

As for the BED file, the expected input is the BED with all TE fragments. Did you generate it with the helper script `SoloTE_RepeatMasker_to_BED.py` ?

**Comment by OwenHoare1989** [comment]
Hi @bvaldebenitom 

Thank you very kindly for your promt reply. I am indeed using a conda environment and have made sure all of the dependencies are installed. I was using python version 3.7 but have since updated to python 3.9. I have included, samtools, bedtools, pysam, pandas and installed R 4.3.1. All versions of the tools should be compatible with the SoloTE pipeline. 

I am re-running the pipeline again and will let you know if it completes successfully. As for the BED file being generated with SoloTE_RepeatMasker_to_BED.py, for the moment I did use this to obtain the hg38_rmsk.bed. Its the same as the one you provided in the tutorial. I am using this in the first instance to run the pipeline and separately I will run another analysis with my own BED file containing genes and all TE fragments which will be quite a large BED file as I have millions of TE fragments. I will let you know if my initial analysis using your BED file works. Fingers crossed and thank you very much for your help.

**Comment by OwenHoare1989** [comment]
Hi again @bvaldebenitom 

i come back to you again with an update on my analysis. The old error seems to be resolved. However, now I have new error below. I am not sure where the problem is coming from but my first reaction was this `The index file is older than the data file: Prefix_final.bam.bai` Again I am using the BED file generated using your script SoloTE_RepeatMasker_to_BED.py. I am am now wondering if this is because the gtf file containing the genes and all TE fragments that I used to run the cellranger pipeline and the BAM file output from this is perhaps not compatible with the BED file I am using from the SoloTE pipeline. I think your BED file has family level IDs and superfamily IDs. Perhaps I will have to construct the BED file myself. Do you think this is the problem. Maybe I am wrong ?? 

Please find the error code below.

```
SoloTE started at 16:26:56
[OK] samtools found!
[OK] bedtools found!
SoloTE v1.09 started!
SoloTE Home directory /data/kdi_prod/.kdi/project_workspace_0/1092/acl/44.00/scRNA_seq_TE_Analysis/SoloTE-1.09
SoloTE executed from /data/kdi_prod/.kdi/project_workspace_0/1092/acl/44.00/scRNA_seq_TE_Analysis/SoloTE-1.09
Results will be stored in /data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/output_TEs/NIP_UGS_678_non_T_cells/outs/Output_SoloTE
Input BAM file: /data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/output_TEs/NIP_UGS_678_non_T_cells/outs/possorted_genome_bam.bam
Input TE BED file: /data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/SoloTE-1.09/hg38_rmsk.bed
Currently working in temporary directory: /data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/output_TEs/NIP_UGS_678_non_T_cells/outs/Output_SoloTE/Prefix_SoloTE_temp
Prefix_nogenes_overlappingtes.bam exists in output folder. Skipping this step
Prefix_nogenes_overlappingtes.bed exists in output folder. Skipping this step
Prefix_selectedtes.bed exists in output folder. Skipping this step
Prefix_teannotated.bam exists in output folder. Skipping this step
samtools merge --threads 4 -o - /data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/output_TEs/NIP_UGS_678_non_T_cells/outs/possorted_genome_bam.bam Prefix_teannotated.bam|samtools view -@ 4 -O BAM -o Prefix_final.bam -e 'exists([CB]) && exists([UB]) && exists([GN]) && [CB]!="-" && [UB]!="-" && [GN]!="-"' --keep-tag GN,CB,UB


^Csamtools index Prefix_final.bam
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
^C[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[W::hts_idx_load3] The index file is older than the data file: Prefix_final.bam.bai
^CTraceback (most recent call last):
  File "/data/kdi_prod/.kdi/project_workspace_0/1092/acl/44.00/scRNA_seq_TE_Analysis/SoloTE-1.09/SoloTE_pipeline.py", line 193, in <module>
    pool = Pool(processes=int(cpus))
  File "/data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/CondaEnvscRNA_seq/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/CondaEnvscRNA_seq/lib/python3.9/multiprocessing/pool.py", line 191, in __init__
    self._setup_queues()
  File "/data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/CondaEnvscRNA_seq/lib/python3.9/multiprocessing/pool.py", line 343, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/data/users/ohoare/Analysis_space/Human_RT_SMARCB1_deficient/scRNA_seq_TE_Analysis/CondaEnvscRNA_seq/lib/python3.9/multiprocessing/context.py", line 112, in SimpleQueue
    from .queues import SimpleQueue
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 941, in get_code
  File "<frozen importlib._bootstrap_external>", line 1040, in get_data
 
```

**Comment by OwenHoare1989** [comment]
Hi @bvaldebenitom 

I managed to get the SoloTE pipeline working on my scRNA-seq data. It's working very nicely and the results are already very interesting. Thank you for developing this really cool tool.

**Comment by bvaldebenitom** [comment]
Hi @OwenHoare1989 ,

thanks for letting me know. What was the issue? From the errors above, I think it might have been related to dependencies rather than the BED or GTF files.

**Comment by OwenHoare1989** [comment]
Hi @bvaldebenitom 

Yes you are correct it was the dependencies. My next task is to make a customs made BED file. I will keep it in the same format as the BED you provided. Thanks for developing this pipeline. It's working very well and gives some very nice results on the clustering. Congratulations!!
